apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec: 
  replicas: 4
  selector: 
    matchLabels:
      app: my-app
  template: 
    metadata:
      labels:
        app: my-app


    spec:
      containers:
      - name: my-container
        image: nginx
        ports:
          - containerPort: 80